export const sites = [
  // {
  //   name: "50 Hacks",
  //   slug: "50-hacks",
  //   link: "https://50hacks.co/",
  // },
  // {
  //   name: "daily.dev",
  //   slug: "daily-dev",
  //   link: "https://daily.dev/",
  // },
  // // {
  // //   name: "Patterns.dev",
  // //   slug: "patterns-dev",
  // //   link: "https://www.patterns.dev/",
  // // },
  // {
  //   name: "UX Colors Illustrations Set",
  //   slug: "ux-colors-illustrations-set",
  //   link: "https://www.streamlinehq.com/illustrations/illustrations-multicolor",
  // },
  // {
  //   name: "1 Line Layouts",
  //   slug: "1-line-layouts",
  //   link: "https://1linelayouts.glitch.me/",
  // },
  {
    name: "Sometimes Always | Boutique Online Wine Store",
    slug: "sometimes-always",
    link: "https://sometimesalways.com.au/",
    categories: ["ecommerce"],
    tags: ["vintage"],
  },
  // {
  //   name: "K72 Agency",
  //   slug: "k72-agency",
  //   link: "https://k72.ca",
  // },
  // {
  //   name: "Studio Ouam",
  //   slug: "studio-ouam",
  //   link: "https://studioouam.com/en",
  // },
  // {
  //   name: "Jonas Reymondin - Creative Front-end Developer",
  //   slug: "jonas-reymondin",
  //   link: "https://www.jonasreymondin.com/",
  // },
  {
    name: "Crazy about Eggs",
    slug: "crazy-about-eggs",
    link: "https://crazyabouteggs.com/",
    categories: ["food", "ecommerce"],
    tags: ["colorful", "illustrations", "nice-typography"],
  },
  // {
  //   name: "Wisr: For Smarter Money Decisions",
  //   slug: "wisr",
  //   link: "https://wisr.com.au/",
  // },
  // {
  //   name: "Emergence Magazine",
  //   slug: "emergence-magazine",
  //   link: "https://emergencemagazine.org/",
  // },
  // {
  //   name: "Baker Mountain Guides",
  //   slug: "baker-mountain-guides",
  //   link: "https://www.bakermountainguides.com/",
  // },
  // {
  //   name: "The Outline",
  //   slug: "outline",
  //   link: "https://theoutline.com/",
  // },
  {
    name: "Il Letterista - Hand-painted Signs",
    slug: "il-letterista",
    link: "https://www.illetterista.it/en/#",
    categories: ["ecommerce"],
    tags: ["vintage", "nice-typography", "illustrations"],
  },
  // {
  //   name: "EPIC Agency",
  //   slug: "epic-agency",
  //   link: "https://www.epic.net/",
  // },
  // {
  //   name: "Neker",
  //   slug: "neker",
  //   link: "https://neker.co.kr/",
  // },
  // {
  //   name: "AR.MOUR | Product Design, Branding & Strategy Agency",
  //   slug: "armour",
  //   link: "https://armour.agency/",
  // },
  // {
  //   name: "Otterdev",
  //   slug: "otterdev",
  //   link: "https://www.otterdev.io/",
  // },
  // {
  //   name: "Kffein - Web agency in Montreal",
  //   slug: "kffein",
  //   link: "https://kffein.com/en/",
  // },
  // {
  //   name: "Aurélia Durand - Portfolio",
  //   slug: "aurelia-durand",
  //   link: "https://www.aurelia-studio.com/",
  // },
  // {
  //   name: "Antara Studio",
  //   slug: "antara-studio",
  //   link: "https://antara.studio/",
  // },
  // {
  //   name: "GOOD Meat",
  //   slug: "good-meat",
  //   link: "https://www.goodmeat.co/",
  // },
  // {
  //   name: "Digital Surgeons - We Design Demand",
  //   slug: "digital-surgeons",
  //   link: "https://www.digitalsurgeons.com/",
  // },
  {
    name: "hdoro.dev",
    slug: "hdoro-dev",
    link: "https://hdoro.dev/",
    categories: ["agency"],
    tags: ["minimal"],
  },
  // {
  //   name: "Iron Velvet - Digital experiences studio from France",
  //   slug: "iron-velvet",
  //   link: "https://ironvelvet.studio/",
  // },
  // // {
  // //   name: "Artistsweb | Award-Winning Digital Agency London Web Design Company",
  // //   slug: "artistsweb",
  // //   link: "https://www.artistsweb.com/",
  // // },
  // {
  //   name: "Wild Souls — Taste the Wild. Find your Soul.",
  //   slug: "wild-souls",
  //   link: "https://www.wildsouls.gr/en",
  // },
  // {
  //   name: "Bonjour Paris",
  //   slug: "bonjour-paris",
  //   link: "https://bonjour.paris/en",
  // },
  // {
  //   name: "Style Stage from Modern CSS Solutions",
  //   slug: "style-stage",
  //   link: "https://stylestage.dev/",
  // },
  // {
  //   name: "Modern CSS Solutions",
  //   slug: "modern-css-solutions",
  //   link: "https://moderncss.dev/",
  // },
  // {
  //   name: "SmolCSS",
  //   slug: "smolcss",
  //   link: "https://smolcss.dev/",
  // },
  // {
  //   name: "Third and Grove",
  //   slug: "third-and-grove",
  //   link: "https://www.thirdandgrove.com/",
  // },
  // {
  //   name: "Bruno, web agency based in California and Normandy.",
  //   slug: "bruno",
  //   link: "https://www.callbruno.com/en/",
  // },
  // {
  //   name: "Khalil Stemmler",
  //   slug: "khalil-stemmler",
  //   link: "https://khalilstemmler.com/",
  // },
  {
    name: "Lamanna - Bakery",
    slug: "lamanna-bakery",
    link: "https://www.lamannabakery.com/",
    categories: ["food"],
    tags: ["colorful", "nice-typography"],
  },
  // {
  //   name: "Typography Principles",
  //   slug: "typography-principles",
  //   link: "https://typographyprinciples.obys.agency/",
  // },
  {
    name: "Increment",
    slug: "increment",
    link: "https://increment.com/",
    categories: ["blog"],
    tags: ["nice-typography", "minimal"],
  },
  {
    name: "GROVE LUST x Creative digital studio",
    slug: "grove-lust",
    link: "https://www.grovelust.be/",
    categories: ["agency"],
    tags: ["colorful"],
  },
  {
    name: "Sennep - Digital product studio",
    slug: "sennep",
    link: "https://www.sennep.com/",
    categories: ["agency"],
    tags: ["colorful", "whimsical"],
  },
  {
    name: "Koval Web",
    slug: "koval-web",
    link: "https://kovalweb.com/",
    categories: ["agency"],
    tags: ["minimal"],
  },
  // {
  //   name: "Inverse Paradox",
  //   slug: "inverse-paradox",
  //   link: "https://www.inverseparadox.com/",
  // },
  // {
  //   name: "Amplience",
  //   slug: "amplience",
  //   link: "https://amplience.com/",
  // },
  // {
  //   name: "GRAYBOX",
  //   slug: "graybox",
  //   link: "https://graybox.co/",
  // },
  // {
  //   name: "Gorilla 76",
  //   slug: "gorilla-76",
  //   link: "https://www.gorilla76.com/",
  // },
  // {
  //   name: "KD Capital",
  //   slug: "kd-capital",
  //   link: "https://kdcap.com/",
  // },
  // {
  //   name: "14islands | Creative design & development studio.",
  //   slug: "14-islands",
  //   link: "https://14islands.com/",
  // },
  // {
  //   name: "Reed, une agence pour votre stratégie digitale",
  //   slug: "reed",
  //   link: "https://www.reed.be/",
  // },
  // {
  //   name: "Army8 - Digital marketing agency in Boston",
  //   slug: "army8",
  //   link: "https://army8.com/",
  // },
  // {
  //   name: "SUMO Heavy | Digital Commerce Strategy | Philadelphia",
  //   slug: "sumo-heavy",
  //   link: "https://www.sumoheavy.com/",
  // },
  // {
  //   name: "Trellis Inc.",
  //   slug: "trellis-inc",
  //   link: "https://www.trellis.co/",
  // },
  // {
  //   name: "Dunderville",
  //   slug: "dunderville",
  //   link: "https://dunderville.se/",
  // },
  // {
  //   name: "Cuberto — Leading digital agency",
  //   slug: "cuberto",
  //   link: "https://cuberto.com",
  // },
  // {
  //   name: "Best Real Estate Transaction Management System for Teams - Shaker.io",
  //   slug: "shaker",
  //   link: "https://www.shaker.io/transaction-management",
  // },
]
